projects:
  familydoc:
    schemaPath: amplify/backend/api/familydoc/build/schema.graphql
    includes:
      - src/lib/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/lib/graphql
extensions:
  amplify:
    version: 3
