projects:
  familydoc:
    schemaPath: src/components/graphql/schema.json
    includes:
      - src/components/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/components/graphql
extensions:
  amplify:
    version: 3
